/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as NewsRouteImport } from './routes/news'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ResourcesRouteRouteImport } from './routes/resources/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as StudioProductsRouteImport } from './routes/studio/products'
import { Route as StudioPagesRouteImport } from './routes/studio/pages'
import { Route as StudioOrdersRouteImport } from './routes/studio/orders'
import { Route as StudioNewsRouteImport } from './routes/studio/news'
import { Route as StudioEventsRouteImport } from './routes/studio/events'
import { Route as StudioCustomersRouteImport } from './routes/studio/customers'
import { Route as StudioCollectionsRouteImport } from './routes/studio/collections'
import { Route as StudioAwardsRouteImport } from './routes/studio/awards'
import { Route as ResourcesResourceIdRouteImport } from './routes/resources/$resourceId'
import { Route as PagesPageIdRouteImport } from './routes/pages/$pageId'
import { Route as DocsStudioRouteImport } from './routes/docs/studio'
import { Route as DocsSitemapRouteImport } from './routes/docs/sitemap'
import { Route as DocsServicesRouteImport } from './routes/docs/services'
import { Route as DocsProcessRouteImport } from './routes/docs/process'
import { Route as DocsBriefRouteImport } from './routes/docs/brief'
import { Route as DocsArchitectureRouteImport } from './routes/docs/architecture'
import { Route as DocsAppendixRouteImport } from './routes/docs/appendix'
import { Route as DocsAdminRouteImport } from './routes/docs/admin'
import { Route as ChaptersNewsRouteImport } from './routes/chapters/news'
import { Route as ChaptersEventsRouteImport } from './routes/chapters/events'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters/$chapterId'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminAwardsRouteImport } from './routes/admin/awards'
import { Route as AccountUpgradeRouteImport } from './routes/account/upgrade'
import { Route as AccountSubscriptionRouteImport } from './routes/account/subscription'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountInvoicesRouteImport } from './routes/account/invoices'
import { Route as AccountEventsRouteImport } from './routes/account/events'
import { Route as AccountAwardsRouteImport } from './routes/account/awards'
import { Route as AccountEducationRouteRouteImport } from './routes/account/education/route'
import { Route as ChaptersChapterIdIndexRouteImport } from './routes/chapters/$chapterId/index'
import { Route as AccountEducationIndexRouteImport } from './routes/account/education/index'
import { Route as DocsAppendixWordpressRouteImport } from './routes/docs/appendix/wordpress'
import { Route as ChaptersChapterIdNewsRouteImport } from './routes/chapters/$chapterId/news'
import { Route as ChaptersChapterIdGalleryRouteImport } from './routes/chapters/$chapterId/gallery'
import { Route as ChaptersChapterIdEventsRouteImport } from './routes/chapters/$chapterId/events'
import { Route as ChaptersChapterIdAwardsRouteImport } from './routes/chapters/$chapterId/awards'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as AccountEducationWebinarsRouteImport } from './routes/account/education/webinars'
import { Route as AccountEducationResourcesRouteImport } from './routes/account/education/resources'
import { Route as AccountEducationCpdRouteImport } from './routes/account/education/cpd'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRouteRoute = ResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const StudioProductsRoute = StudioProductsRouteImport.update({
  id: '/studio/products',
  path: '/studio/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPagesRoute = StudioPagesRouteImport.update({
  id: '/studio/pages',
  path: '/studio/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioOrdersRoute = StudioOrdersRouteImport.update({
  id: '/studio/orders',
  path: '/studio/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioNewsRoute = StudioNewsRouteImport.update({
  id: '/studio/news',
  path: '/studio/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioEventsRoute = StudioEventsRouteImport.update({
  id: '/studio/events',
  path: '/studio/events',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCustomersRoute = StudioCustomersRouteImport.update({
  id: '/studio/customers',
  path: '/studio/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCollectionsRoute = StudioCollectionsRouteImport.update({
  id: '/studio/collections',
  path: '/studio/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAwardsRoute = StudioAwardsRouteImport.update({
  id: '/studio/awards',
  path: '/studio/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesResourceIdRoute = ResourcesResourceIdRouteImport.update({
  id: '/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioRoute = DocsStudioRouteImport.update({
  id: '/docs/studio',
  path: '/docs/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSitemapRoute = DocsSitemapRouteImport.update({
  id: '/docs/sitemap',
  path: '/docs/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsServicesRoute = DocsServicesRouteImport.update({
  id: '/docs/services',
  path: '/docs/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProcessRoute = DocsProcessRouteImport.update({
  id: '/docs/process',
  path: '/docs/process',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBriefRoute = DocsBriefRouteImport.update({
  id: '/docs/brief',
  path: '/docs/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/docs/architecture',
  path: '/docs/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAppendixRoute = DocsAppendixRouteImport.update({
  id: '/docs/appendix',
  path: '/docs/appendix',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminRoute = DocsAdminRouteImport.update({
  id: '/docs/admin',
  path: '/docs/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersNewsRoute = ChaptersNewsRouteImport.update({
  id: '/chapters/news',
  path: '/chapters/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersEventsRoute = ChaptersEventsRouteImport.update({
  id: '/chapters/events',
  path: '/chapters/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/admin/memberships',
  path: '/admin/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/admin/awards',
  path: '/admin/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUpgradeRoute = AccountUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSubscriptionRoute = AccountSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountInvoicesRoute = AccountInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountEventsRoute = AccountEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAwardsRoute = AccountAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountEducationRouteRoute = AccountEducationRouteRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ChaptersChapterIdIndexRoute = ChaptersChapterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const AccountEducationIndexRoute = AccountEducationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountEducationRouteRoute,
} as any)
const DocsAppendixWordpressRoute = DocsAppendixWordpressRouteImport.update({
  id: '/wordpress',
  path: '/wordpress',
  getParentRoute: () => DocsAppendixRoute,
} as any)
const ChaptersChapterIdNewsRoute = ChaptersChapterIdNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const ChaptersChapterIdGalleryRoute =
  ChaptersChapterIdGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => ChaptersChapterIdRoute,
  } as any)
const ChaptersChapterIdEventsRoute = ChaptersChapterIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const ChaptersChapterIdAwardsRoute = ChaptersChapterIdAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEducationWebinarsRoute =
  AccountEducationWebinarsRouteImport.update({
    id: '/webinars',
    path: '/webinars',
    getParentRoute: () => AccountEducationRouteRoute,
  } as any)
const AccountEducationResourcesRoute =
  AccountEducationResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AccountEducationRouteRoute,
  } as any)
const AccountEducationCpdRoute = AccountEducationCpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => AccountEducationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/store': typeof StoreRoute
  '/account/education': typeof AccountEducationRouteRouteWithChildren
  '/account/awards': typeof AccountAwardsRoute
  '/account/events': typeof AccountEventsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRouteWithChildren
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/news': typeof ChaptersNewsRoute
  '/docs/admin': typeof DocsAdminRoute
  '/docs/appendix': typeof DocsAppendixRouteWithChildren
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/brief': typeof DocsBriefRoute
  '/docs/process': typeof DocsProcessRoute
  '/docs/services': typeof DocsServicesRoute
  '/docs/sitemap': typeof DocsSitemapRoute
  '/docs/studio': typeof DocsStudioRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/studio/awards': typeof StudioAwardsRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/customers': typeof StudioCustomersRoute
  '/studio/events': typeof StudioEventsRoute
  '/studio/news': typeof StudioNewsRoute
  '/studio/orders': typeof StudioOrdersRoute
  '/studio/pages': typeof StudioPagesRoute
  '/studio/products': typeof StudioProductsRoute
  '/account/': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/chapters': typeof ChaptersIndexRoute
  '/docs': typeof DocsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/studio': typeof StudioIndexRoute
  '/account/education/cpd': typeof AccountEducationCpdRoute
  '/account/education/resources': typeof AccountEducationResourcesRoute
  '/account/education/webinars': typeof AccountEducationWebinarsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chapters/$chapterId/awards': typeof ChaptersChapterIdAwardsRoute
  '/chapters/$chapterId/events': typeof ChaptersChapterIdEventsRoute
  '/chapters/$chapterId/gallery': typeof ChaptersChapterIdGalleryRoute
  '/chapters/$chapterId/news': typeof ChaptersChapterIdNewsRoute
  '/docs/appendix/wordpress': typeof DocsAppendixWordpressRoute
  '/account/education/': typeof AccountEducationIndexRoute
  '/chapters/$chapterId/': typeof ChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/store': typeof StoreRoute
  '/account/awards': typeof AccountAwardsRoute
  '/account/events': typeof AccountEventsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/news': typeof ChaptersNewsRoute
  '/docs/admin': typeof DocsAdminRoute
  '/docs/appendix': typeof DocsAppendixRouteWithChildren
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/brief': typeof DocsBriefRoute
  '/docs/process': typeof DocsProcessRoute
  '/docs/services': typeof DocsServicesRoute
  '/docs/sitemap': typeof DocsSitemapRoute
  '/docs/studio': typeof DocsStudioRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/studio/awards': typeof StudioAwardsRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/customers': typeof StudioCustomersRoute
  '/studio/events': typeof StudioEventsRoute
  '/studio/news': typeof StudioNewsRoute
  '/studio/orders': typeof StudioOrdersRoute
  '/studio/pages': typeof StudioPagesRoute
  '/studio/products': typeof StudioProductsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/chapters': typeof ChaptersIndexRoute
  '/docs': typeof DocsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/studio': typeof StudioIndexRoute
  '/account/education/cpd': typeof AccountEducationCpdRoute
  '/account/education/resources': typeof AccountEducationResourcesRoute
  '/account/education/webinars': typeof AccountEducationWebinarsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chapters/$chapterId/awards': typeof ChaptersChapterIdAwardsRoute
  '/chapters/$chapterId/events': typeof ChaptersChapterIdEventsRoute
  '/chapters/$chapterId/gallery': typeof ChaptersChapterIdGalleryRoute
  '/chapters/$chapterId/news': typeof ChaptersChapterIdNewsRoute
  '/docs/appendix/wordpress': typeof DocsAppendixWordpressRoute
  '/account/education': typeof AccountEducationIndexRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/store': typeof StoreRoute
  '/account/education': typeof AccountEducationRouteRouteWithChildren
  '/account/awards': typeof AccountAwardsRoute
  '/account/events': typeof AccountEventsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRouteWithChildren
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/news': typeof ChaptersNewsRoute
  '/docs/admin': typeof DocsAdminRoute
  '/docs/appendix': typeof DocsAppendixRouteWithChildren
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/brief': typeof DocsBriefRoute
  '/docs/process': typeof DocsProcessRoute
  '/docs/services': typeof DocsServicesRoute
  '/docs/sitemap': typeof DocsSitemapRoute
  '/docs/studio': typeof DocsStudioRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/studio/awards': typeof StudioAwardsRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/customers': typeof StudioCustomersRoute
  '/studio/events': typeof StudioEventsRoute
  '/studio/news': typeof StudioNewsRoute
  '/studio/orders': typeof StudioOrdersRoute
  '/studio/pages': typeof StudioPagesRoute
  '/studio/products': typeof StudioProductsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/account/education/cpd': typeof AccountEducationCpdRoute
  '/account/education/resources': typeof AccountEducationResourcesRoute
  '/account/education/webinars': typeof AccountEducationWebinarsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chapters/$chapterId/awards': typeof ChaptersChapterIdAwardsRoute
  '/chapters/$chapterId/events': typeof ChaptersChapterIdEventsRoute
  '/chapters/$chapterId/gallery': typeof ChaptersChapterIdGalleryRoute
  '/chapters/$chapterId/news': typeof ChaptersChapterIdNewsRoute
  '/docs/appendix/wordpress': typeof DocsAppendixWordpressRoute
  '/account/education/': typeof AccountEducationIndexRoute
  '/chapters/$chapterId/': typeof ChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/resources'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/conferences'
    | '/contact'
    | '/events'
    | '/news'
    | '/store'
    | '/account/education'
    | '/account/awards'
    | '/account/events'
    | '/account/invoices'
    | '/account/login'
    | '/account/profile'
    | '/account/subscription'
    | '/account/upgrade'
    | '/admin/awards'
    | '/admin/content'
    | '/admin/events'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/chapters/$chapterId'
    | '/chapters/events'
    | '/chapters/news'
    | '/docs/admin'
    | '/docs/appendix'
    | '/docs/architecture'
    | '/docs/brief'
    | '/docs/process'
    | '/docs/services'
    | '/docs/sitemap'
    | '/docs/studio'
    | '/pages/$pageId'
    | '/resources/$resourceId'
    | '/studio/awards'
    | '/studio/collections'
    | '/studio/customers'
    | '/studio/events'
    | '/studio/news'
    | '/studio/orders'
    | '/studio/pages'
    | '/studio/products'
    | '/account/'
    | '/admin'
    | '/chapters'
    | '/docs'
    | '/resources/'
    | '/studio'
    | '/account/education/cpd'
    | '/account/education/resources'
    | '/account/education/webinars'
    | '/api/trpc/$'
    | '/chapters/$chapterId/awards'
    | '/chapters/$chapterId/events'
    | '/chapters/$chapterId/gallery'
    | '/chapters/$chapterId/news'
    | '/docs/appendix/wordpress'
    | '/account/education/'
    | '/chapters/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/conferences'
    | '/contact'
    | '/events'
    | '/news'
    | '/store'
    | '/account/awards'
    | '/account/events'
    | '/account/invoices'
    | '/account/login'
    | '/account/profile'
    | '/account/subscription'
    | '/account/upgrade'
    | '/admin/awards'
    | '/admin/content'
    | '/admin/events'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/chapters/events'
    | '/chapters/news'
    | '/docs/admin'
    | '/docs/appendix'
    | '/docs/architecture'
    | '/docs/brief'
    | '/docs/process'
    | '/docs/services'
    | '/docs/sitemap'
    | '/docs/studio'
    | '/pages/$pageId'
    | '/resources/$resourceId'
    | '/studio/awards'
    | '/studio/collections'
    | '/studio/customers'
    | '/studio/events'
    | '/studio/news'
    | '/studio/orders'
    | '/studio/pages'
    | '/studio/products'
    | '/account'
    | '/admin'
    | '/chapters'
    | '/docs'
    | '/resources'
    | '/studio'
    | '/account/education/cpd'
    | '/account/education/resources'
    | '/account/education/webinars'
    | '/api/trpc/$'
    | '/chapters/$chapterId/awards'
    | '/chapters/$chapterId/events'
    | '/chapters/$chapterId/gallery'
    | '/chapters/$chapterId/news'
    | '/docs/appendix/wordpress'
    | '/account/education'
    | '/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/resources'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/conferences'
    | '/contact'
    | '/events'
    | '/news'
    | '/store'
    | '/account/education'
    | '/account/awards'
    | '/account/events'
    | '/account/invoices'
    | '/account/login'
    | '/account/profile'
    | '/account/subscription'
    | '/account/upgrade'
    | '/admin/awards'
    | '/admin/content'
    | '/admin/events'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/chapters/$chapterId'
    | '/chapters/events'
    | '/chapters/news'
    | '/docs/admin'
    | '/docs/appendix'
    | '/docs/architecture'
    | '/docs/brief'
    | '/docs/process'
    | '/docs/services'
    | '/docs/sitemap'
    | '/docs/studio'
    | '/pages/$pageId'
    | '/resources/$resourceId'
    | '/studio/awards'
    | '/studio/collections'
    | '/studio/customers'
    | '/studio/events'
    | '/studio/news'
    | '/studio/orders'
    | '/studio/pages'
    | '/studio/products'
    | '/account/'
    | '/admin/'
    | '/chapters/'
    | '/docs/'
    | '/resources/'
    | '/studio/'
    | '/account/education/cpd'
    | '/account/education/resources'
    | '/account/education/webinars'
    | '/api/trpc/$'
    | '/chapters/$chapterId/awards'
    | '/chapters/$chapterId/events'
    | '/chapters/$chapterId/gallery'
    | '/chapters/$chapterId/news'
    | '/docs/appendix/wordpress'
    | '/account/education/'
    | '/chapters/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  ResourcesRouteRoute: typeof ResourcesRouteRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  CalendarRoute: typeof CalendarRoute
  CartRoute: typeof CartRoute
  ConferencesRoute: typeof ConferencesRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  NewsRoute: typeof NewsRoute
  StoreRoute: typeof StoreRoute
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRouteWithChildren
  ChaptersEventsRoute: typeof ChaptersEventsRoute
  ChaptersNewsRoute: typeof ChaptersNewsRoute
  DocsAdminRoute: typeof DocsAdminRoute
  DocsAppendixRoute: typeof DocsAppendixRouteWithChildren
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsBriefRoute: typeof DocsBriefRoute
  DocsProcessRoute: typeof DocsProcessRoute
  DocsServicesRoute: typeof DocsServicesRoute
  DocsSitemapRoute: typeof DocsSitemapRoute
  DocsStudioRoute: typeof DocsStudioRoute
  PagesPageIdRoute: typeof PagesPageIdRoute
  StudioAwardsRoute: typeof StudioAwardsRoute
  StudioCollectionsRoute: typeof StudioCollectionsRoute
  StudioCustomersRoute: typeof StudioCustomersRoute
  StudioEventsRoute: typeof StudioEventsRoute
  StudioNewsRoute: typeof StudioNewsRoute
  StudioOrdersRoute: typeof StudioOrdersRoute
  StudioPagesRoute: typeof StudioPagesRoute
  StudioProductsRoute: typeof StudioProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/studio/products': {
      id: '/studio/products'
      path: '/studio/products'
      fullPath: '/studio/products'
      preLoaderRoute: typeof StudioProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/pages': {
      id: '/studio/pages'
      path: '/studio/pages'
      fullPath: '/studio/pages'
      preLoaderRoute: typeof StudioPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/orders': {
      id: '/studio/orders'
      path: '/studio/orders'
      fullPath: '/studio/orders'
      preLoaderRoute: typeof StudioOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/news': {
      id: '/studio/news'
      path: '/studio/news'
      fullPath: '/studio/news'
      preLoaderRoute: typeof StudioNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/events': {
      id: '/studio/events'
      path: '/studio/events'
      fullPath: '/studio/events'
      preLoaderRoute: typeof StudioEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/customers': {
      id: '/studio/customers'
      path: '/studio/customers'
      fullPath: '/studio/customers'
      preLoaderRoute: typeof StudioCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/collections': {
      id: '/studio/collections'
      path: '/studio/collections'
      fullPath: '/studio/collections'
      preLoaderRoute: typeof StudioCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/awards': {
      id: '/studio/awards'
      path: '/studio/awards'
      fullPath: '/studio/awards'
      preLoaderRoute: typeof StudioAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$resourceId': {
      id: '/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof ResourcesResourceIdRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio': {
      id: '/docs/studio'
      path: '/docs/studio'
      fullPath: '/docs/studio'
      preLoaderRoute: typeof DocsStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/sitemap': {
      id: '/docs/sitemap'
      path: '/docs/sitemap'
      fullPath: '/docs/sitemap'
      preLoaderRoute: typeof DocsSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/services': {
      id: '/docs/services'
      path: '/docs/services'
      fullPath: '/docs/services'
      preLoaderRoute: typeof DocsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/process': {
      id: '/docs/process'
      path: '/docs/process'
      fullPath: '/docs/process'
      preLoaderRoute: typeof DocsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/brief': {
      id: '/docs/brief'
      path: '/docs/brief'
      fullPath: '/docs/brief'
      preLoaderRoute: typeof DocsBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/docs/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/appendix': {
      id: '/docs/appendix'
      path: '/docs/appendix'
      fullPath: '/docs/appendix'
      preLoaderRoute: typeof DocsAppendixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin': {
      id: '/docs/admin'
      path: '/docs/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/news': {
      id: '/chapters/news'
      path: '/chapters/news'
      fullPath: '/chapters/news'
      preLoaderRoute: typeof ChaptersNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/events': {
      id: '/chapters/events'
      path: '/chapters/events'
      fullPath: '/chapters/events'
      preLoaderRoute: typeof ChaptersEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/admin/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/admin/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/upgrade': {
      id: '/account/upgrade'
      path: '/upgrade'
      fullPath: '/account/upgrade'
      preLoaderRoute: typeof AccountUpgradeRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/subscription': {
      id: '/account/subscription'
      path: '/subscription'
      fullPath: '/account/subscription'
      preLoaderRoute: typeof AccountSubscriptionRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/invoices': {
      id: '/account/invoices'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AccountInvoicesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/events': {
      id: '/account/events'
      path: '/events'
      fullPath: '/account/events'
      preLoaderRoute: typeof AccountEventsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/awards': {
      id: '/account/awards'
      path: '/awards'
      fullPath: '/account/awards'
      preLoaderRoute: typeof AccountAwardsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/education': {
      id: '/account/education'
      path: '/education'
      fullPath: '/account/education'
      preLoaderRoute: typeof AccountEducationRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/chapters/$chapterId/': {
      id: '/chapters/$chapterId/'
      path: '/'
      fullPath: '/chapters/$chapterId/'
      preLoaderRoute: typeof ChaptersChapterIdIndexRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/account/education/': {
      id: '/account/education/'
      path: '/'
      fullPath: '/account/education/'
      preLoaderRoute: typeof AccountEducationIndexRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
    '/docs/appendix/wordpress': {
      id: '/docs/appendix/wordpress'
      path: '/wordpress'
      fullPath: '/docs/appendix/wordpress'
      preLoaderRoute: typeof DocsAppendixWordpressRouteImport
      parentRoute: typeof DocsAppendixRoute
    }
    '/chapters/$chapterId/news': {
      id: '/chapters/$chapterId/news'
      path: '/news'
      fullPath: '/chapters/$chapterId/news'
      preLoaderRoute: typeof ChaptersChapterIdNewsRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/chapters/$chapterId/gallery': {
      id: '/chapters/$chapterId/gallery'
      path: '/gallery'
      fullPath: '/chapters/$chapterId/gallery'
      preLoaderRoute: typeof ChaptersChapterIdGalleryRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/chapters/$chapterId/events': {
      id: '/chapters/$chapterId/events'
      path: '/events'
      fullPath: '/chapters/$chapterId/events'
      preLoaderRoute: typeof ChaptersChapterIdEventsRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/chapters/$chapterId/awards': {
      id: '/chapters/$chapterId/awards'
      path: '/awards'
      fullPath: '/chapters/$chapterId/awards'
      preLoaderRoute: typeof ChaptersChapterIdAwardsRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/education/webinars': {
      id: '/account/education/webinars'
      path: '/webinars'
      fullPath: '/account/education/webinars'
      preLoaderRoute: typeof AccountEducationWebinarsRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
    '/account/education/resources': {
      id: '/account/education/resources'
      path: '/resources'
      fullPath: '/account/education/resources'
      preLoaderRoute: typeof AccountEducationResourcesRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
    '/account/education/cpd': {
      id: '/account/education/cpd'
      path: '/cpd'
      fullPath: '/account/education/cpd'
      preLoaderRoute: typeof AccountEducationCpdRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
  }
}

interface AccountEducationRouteRouteChildren {
  AccountEducationCpdRoute: typeof AccountEducationCpdRoute
  AccountEducationResourcesRoute: typeof AccountEducationResourcesRoute
  AccountEducationWebinarsRoute: typeof AccountEducationWebinarsRoute
  AccountEducationIndexRoute: typeof AccountEducationIndexRoute
}

const AccountEducationRouteRouteChildren: AccountEducationRouteRouteChildren = {
  AccountEducationCpdRoute: AccountEducationCpdRoute,
  AccountEducationResourcesRoute: AccountEducationResourcesRoute,
  AccountEducationWebinarsRoute: AccountEducationWebinarsRoute,
  AccountEducationIndexRoute: AccountEducationIndexRoute,
}

const AccountEducationRouteRouteWithChildren =
  AccountEducationRouteRoute._addFileChildren(
    AccountEducationRouteRouteChildren,
  )

interface AccountRouteRouteChildren {
  AccountEducationRouteRoute: typeof AccountEducationRouteRouteWithChildren
  AccountAwardsRoute: typeof AccountAwardsRoute
  AccountEventsRoute: typeof AccountEventsRoute
  AccountInvoicesRoute: typeof AccountInvoicesRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSubscriptionRoute: typeof AccountSubscriptionRoute
  AccountUpgradeRoute: typeof AccountUpgradeRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountEducationRouteRoute: AccountEducationRouteRouteWithChildren,
  AccountAwardsRoute: AccountAwardsRoute,
  AccountEventsRoute: AccountEventsRoute,
  AccountInvoicesRoute: AccountInvoicesRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSubscriptionRoute: AccountSubscriptionRoute,
  AccountUpgradeRoute: AccountUpgradeRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface ResourcesRouteRouteChildren {
  ResourcesResourceIdRoute: typeof ResourcesResourceIdRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteRouteChildren: ResourcesRouteRouteChildren = {
  ResourcesResourceIdRoute: ResourcesResourceIdRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteRouteWithChildren = ResourcesRouteRoute._addFileChildren(
  ResourcesRouteRouteChildren,
)

interface ChaptersChapterIdRouteChildren {
  ChaptersChapterIdAwardsRoute: typeof ChaptersChapterIdAwardsRoute
  ChaptersChapterIdEventsRoute: typeof ChaptersChapterIdEventsRoute
  ChaptersChapterIdGalleryRoute: typeof ChaptersChapterIdGalleryRoute
  ChaptersChapterIdNewsRoute: typeof ChaptersChapterIdNewsRoute
  ChaptersChapterIdIndexRoute: typeof ChaptersChapterIdIndexRoute
}

const ChaptersChapterIdRouteChildren: ChaptersChapterIdRouteChildren = {
  ChaptersChapterIdAwardsRoute: ChaptersChapterIdAwardsRoute,
  ChaptersChapterIdEventsRoute: ChaptersChapterIdEventsRoute,
  ChaptersChapterIdGalleryRoute: ChaptersChapterIdGalleryRoute,
  ChaptersChapterIdNewsRoute: ChaptersChapterIdNewsRoute,
  ChaptersChapterIdIndexRoute: ChaptersChapterIdIndexRoute,
}

const ChaptersChapterIdRouteWithChildren =
  ChaptersChapterIdRoute._addFileChildren(ChaptersChapterIdRouteChildren)

interface DocsAppendixRouteChildren {
  DocsAppendixWordpressRoute: typeof DocsAppendixWordpressRoute
}

const DocsAppendixRouteChildren: DocsAppendixRouteChildren = {
  DocsAppendixWordpressRoute: DocsAppendixWordpressRoute,
}

const DocsAppendixRouteWithChildren = DocsAppendixRoute._addFileChildren(
  DocsAppendixRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  ResourcesRouteRoute: ResourcesRouteRouteWithChildren,
  AwardsRoute: AwardsRoute,
  CalendarRoute: CalendarRoute,
  CartRoute: CartRoute,
  ConferencesRoute: ConferencesRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  NewsRoute: NewsRoute,
  StoreRoute: StoreRoute,
  AdminAwardsRoute: AdminAwardsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRouteWithChildren,
  ChaptersEventsRoute: ChaptersEventsRoute,
  ChaptersNewsRoute: ChaptersNewsRoute,
  DocsAdminRoute: DocsAdminRoute,
  DocsAppendixRoute: DocsAppendixRouteWithChildren,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsBriefRoute: DocsBriefRoute,
  DocsProcessRoute: DocsProcessRoute,
  DocsServicesRoute: DocsServicesRoute,
  DocsSitemapRoute: DocsSitemapRoute,
  DocsStudioRoute: DocsStudioRoute,
  PagesPageIdRoute: PagesPageIdRoute,
  StudioAwardsRoute: StudioAwardsRoute,
  StudioCollectionsRoute: StudioCollectionsRoute,
  StudioCustomersRoute: StudioCustomersRoute,
  StudioEventsRoute: StudioEventsRoute,
  StudioNewsRoute: StudioNewsRoute,
  StudioOrdersRoute: StudioOrdersRoute,
  StudioPagesRoute: StudioPagesRoute,
  StudioProductsRoute: StudioProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
