/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as NewsRouteImport } from './routes/news'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ResourcesRouteRouteImport } from './routes/resources/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ConferencesIndexRouteImport } from './routes/conferences/index'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as StudioProductsRouteImport } from './routes/studio/products'
import { Route as StudioPagesRouteImport } from './routes/studio/pages'
import { Route as StudioOrdersRouteImport } from './routes/studio/orders'
import { Route as StudioNewsRouteImport } from './routes/studio/news'
import { Route as StudioEventsRouteImport } from './routes/studio/events'
import { Route as StudioCustomersRouteImport } from './routes/studio/customers'
import { Route as StudioCollectionsRouteImport } from './routes/studio/collections'
import { Route as StudioAwardsRouteImport } from './routes/studio/awards'
import { Route as ResourcesResourceIdRouteImport } from './routes/resources/$resourceId'
import { Route as PagesPageIdRouteImport } from './routes/pages/$pageId'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as DocsProcessRouteImport } from './routes/docs/process'
import { Route as DocsContentsRouteImport } from './routes/docs/contents'
import { Route as ConferencesConferenceIdRouteImport } from './routes/conferences/$conferenceId'
import { Route as ChaptersNewsRouteImport } from './routes/chapters/news'
import { Route as ChaptersEventsRouteImport } from './routes/chapters/events'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters/$chapterId'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminAwardsRouteImport } from './routes/admin/awards'
import { Route as AccountUpgradeRouteImport } from './routes/account/upgrade'
import { Route as AccountSubscriptionRouteImport } from './routes/account/subscription'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountInvoicesRouteImport } from './routes/account/invoices'
import { Route as AccountEventsRouteImport } from './routes/account/events'
import { Route as AccountAwardsRouteImport } from './routes/account/awards'
import { Route as AccountEducationRouteRouteImport } from './routes/account/education/route'
import { Route as DocsVendorIndexRouteImport } from './routes/docs/vendor/index'
import { Route as DocsStudioIndexRouteImport } from './routes/docs/studio/index'
import { Route as DocsGuidanceIndexRouteImport } from './routes/docs/guidance/index'
import { Route as DocsArchitectureIndexRouteImport } from './routes/docs/architecture/index'
import { Route as DocsAppendixIndexRouteImport } from './routes/docs/appendix/index'
import { Route as DocsAdminIndexRouteImport } from './routes/docs/admin/index'
import { Route as ConferencesConferenceIdIndexRouteImport } from './routes/conferences/$conferenceId/index'
import { Route as ChaptersChapterIdIndexRouteImport } from './routes/chapters/$chapterId/index'
import { Route as AccountEducationIndexRouteImport } from './routes/account/education/index'
import { Route as DocsVendorBriefRouteImport } from './routes/docs/vendor/brief'
import { Route as DocsStudioProductsRouteImport } from './routes/docs/studio/products'
import { Route as DocsStudioPagesRouteImport } from './routes/docs/studio/pages'
import { Route as DocsStudioOrdersRouteImport } from './routes/docs/studio/orders'
import { Route as DocsStudioNewsRouteImport } from './routes/docs/studio/news'
import { Route as DocsStudioEventsRouteImport } from './routes/docs/studio/events'
import { Route as DocsStudioCustomersRouteImport } from './routes/docs/studio/customers'
import { Route as DocsStudioCollectionsRouteImport } from './routes/docs/studio/collections'
import { Route as DocsStudioAwardsRouteImport } from './routes/docs/studio/awards'
import { Route as DocsOverviewReverseBriefRouteImport } from './routes/docs/overview/reverse-brief'
import { Route as DocsGuidancePrioritiesRouteImport } from './routes/docs/guidance/priorities'
import { Route as DocsGuidancePhasesRouteImport } from './routes/docs/guidance/phases'
import { Route as DocsArchitectureSitemapRouteImport } from './routes/docs/architecture/sitemap'
import { Route as DocsAppendixWordpressRouteImport } from './routes/docs/appendix/wordpress'
import { Route as DocsAdminSupportRouteImport } from './routes/docs/admin/support'
import { Route as DocsAdminSubmissionsRouteImport } from './routes/docs/admin/submissions'
import { Route as DocsAdminSettingsRouteImport } from './routes/docs/admin/settings'
import { Route as DocsAdminReportsRouteImport } from './routes/docs/admin/reports'
import { Route as DocsAdminPaymentsRouteImport } from './routes/docs/admin/payments'
import { Route as DocsAdminMembershipsRouteImport } from './routes/docs/admin/memberships'
import { Route as DocsAdminMembersRouteImport } from './routes/docs/admin/members'
import { Route as DocsAdminEventsRouteImport } from './routes/docs/admin/events'
import { Route as DocsAdminDashboardRouteImport } from './routes/docs/admin/dashboard'
import { Route as DocsAdminContentRouteImport } from './routes/docs/admin/content'
import { Route as DocsAdminAwardsRouteImport } from './routes/docs/admin/awards'
import { Route as ConferencesConferenceIdTicketsRouteImport } from './routes/conferences/$conferenceId/tickets'
import { Route as ConferencesConferenceIdSponsorsRouteImport } from './routes/conferences/$conferenceId/sponsors'
import { Route as ConferencesConferenceIdSpeakersRouteImport } from './routes/conferences/$conferenceId/speakers'
import { Route as ConferencesConferenceIdProgramRouteImport } from './routes/conferences/$conferenceId/program'
import { Route as ConferencesConferenceIdGalleryRouteImport } from './routes/conferences/$conferenceId/gallery'
import { Route as ChaptersChapterIdNewsRouteImport } from './routes/chapters/$chapterId/news'
import { Route as ChaptersChapterIdGalleryRouteImport } from './routes/chapters/$chapterId/gallery'
import { Route as ChaptersChapterIdEventsRouteImport } from './routes/chapters/$chapterId/events'
import { Route as ChaptersChapterIdAwardsRouteImport } from './routes/chapters/$chapterId/awards'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as AccountEducationWebinarsRouteImport } from './routes/account/education/webinars'
import { Route as AccountEducationResourcesRouteImport } from './routes/account/education/resources'
import { Route as AccountEducationCpdRouteImport } from './routes/account/education/cpd'
import { Route as DocsArchitectureServicesIndexRouteImport } from './routes/docs/architecture/services/index'
import { Route as DocsArchitectureServicesShopifyRouteImport } from './routes/docs/architecture/services/shopify'
import { Route as DocsArchitectureServicesSanityRouteImport } from './routes/docs/architecture/services/sanity'
import { Route as DocsArchitectureServicesKlaviyoRouteImport } from './routes/docs/architecture/services/klaviyo'
import { Route as DocsArchitectureServicesAuth0RouteImport } from './routes/docs/architecture/services/auth0'
import { Route as DocsArchitectureServicesAlgoliaRouteImport } from './routes/docs/architecture/services/algolia'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRouteRoute = ResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesIndexRoute = ConferencesIndexRouteImport.update({
  id: '/conferences/',
  path: '/conferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const StudioProductsRoute = StudioProductsRouteImport.update({
  id: '/studio/products',
  path: '/studio/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPagesRoute = StudioPagesRouteImport.update({
  id: '/studio/pages',
  path: '/studio/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioOrdersRoute = StudioOrdersRouteImport.update({
  id: '/studio/orders',
  path: '/studio/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioNewsRoute = StudioNewsRouteImport.update({
  id: '/studio/news',
  path: '/studio/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioEventsRoute = StudioEventsRouteImport.update({
  id: '/studio/events',
  path: '/studio/events',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCustomersRoute = StudioCustomersRouteImport.update({
  id: '/studio/customers',
  path: '/studio/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCollectionsRoute = StudioCollectionsRouteImport.update({
  id: '/studio/collections',
  path: '/studio/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAwardsRoute = StudioAwardsRouteImport.update({
  id: '/studio/awards',
  path: '/studio/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesResourceIdRoute = ResourcesResourceIdRouteImport.update({
  id: '/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const DocsProcessRoute = DocsProcessRouteImport.update({
  id: '/docs/process',
  path: '/docs/process',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsContentsRoute = DocsContentsRouteImport.update({
  id: '/docs/contents',
  path: '/docs/contents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesConferenceIdRoute = ConferencesConferenceIdRouteImport.update({
  id: '/conferences/$conferenceId',
  path: '/conferences/$conferenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersNewsRoute = ChaptersNewsRouteImport.update({
  id: '/chapters/news',
  path: '/chapters/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersEventsRoute = ChaptersEventsRouteImport.update({
  id: '/chapters/events',
  path: '/chapters/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/admin/memberships',
  path: '/admin/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/admin/awards',
  path: '/admin/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUpgradeRoute = AccountUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSubscriptionRoute = AccountSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountInvoicesRoute = AccountInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountEventsRoute = AccountEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAwardsRoute = AccountAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountEducationRouteRoute = AccountEducationRouteRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AccountRouteRoute,
} as any)
const DocsVendorIndexRoute = DocsVendorIndexRouteImport.update({
  id: '/docs/vendor/',
  path: '/docs/vendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioIndexRoute = DocsStudioIndexRouteImport.update({
  id: '/docs/studio/',
  path: '/docs/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuidanceIndexRoute = DocsGuidanceIndexRouteImport.update({
  id: '/docs/guidance/',
  path: '/docs/guidance/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureIndexRoute = DocsArchitectureIndexRouteImport.update({
  id: '/docs/architecture/',
  path: '/docs/architecture/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAppendixIndexRoute = DocsAppendixIndexRouteImport.update({
  id: '/docs/appendix/',
  path: '/docs/appendix/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminIndexRoute = DocsAdminIndexRouteImport.update({
  id: '/docs/admin/',
  path: '/docs/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesConferenceIdIndexRoute =
  ConferencesConferenceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)
const ChaptersChapterIdIndexRoute = ChaptersChapterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const AccountEducationIndexRoute = AccountEducationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountEducationRouteRoute,
} as any)
const DocsVendorBriefRoute = DocsVendorBriefRouteImport.update({
  id: '/docs/vendor/brief',
  path: '/docs/vendor/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioProductsRoute = DocsStudioProductsRouteImport.update({
  id: '/docs/studio/products',
  path: '/docs/studio/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioPagesRoute = DocsStudioPagesRouteImport.update({
  id: '/docs/studio/pages',
  path: '/docs/studio/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioOrdersRoute = DocsStudioOrdersRouteImport.update({
  id: '/docs/studio/orders',
  path: '/docs/studio/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioNewsRoute = DocsStudioNewsRouteImport.update({
  id: '/docs/studio/news',
  path: '/docs/studio/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioEventsRoute = DocsStudioEventsRouteImport.update({
  id: '/docs/studio/events',
  path: '/docs/studio/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioCustomersRoute = DocsStudioCustomersRouteImport.update({
  id: '/docs/studio/customers',
  path: '/docs/studio/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioCollectionsRoute = DocsStudioCollectionsRouteImport.update({
  id: '/docs/studio/collections',
  path: '/docs/studio/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStudioAwardsRoute = DocsStudioAwardsRouteImport.update({
  id: '/docs/studio/awards',
  path: '/docs/studio/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOverviewReverseBriefRoute =
  DocsOverviewReverseBriefRouteImport.update({
    id: '/docs/overview/reverse-brief',
    path: '/docs/overview/reverse-brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsGuidancePrioritiesRoute = DocsGuidancePrioritiesRouteImport.update({
  id: '/docs/guidance/priorities',
  path: '/docs/guidance/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuidancePhasesRoute = DocsGuidancePhasesRouteImport.update({
  id: '/docs/guidance/phases',
  path: '/docs/guidance/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureSitemapRoute = DocsArchitectureSitemapRouteImport.update({
  id: '/docs/architecture/sitemap',
  path: '/docs/architecture/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAppendixWordpressRoute = DocsAppendixWordpressRouteImport.update({
  id: '/docs/appendix/wordpress',
  path: '/docs/appendix/wordpress',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminSupportRoute = DocsAdminSupportRouteImport.update({
  id: '/docs/admin/support',
  path: '/docs/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminSubmissionsRoute = DocsAdminSubmissionsRouteImport.update({
  id: '/docs/admin/submissions',
  path: '/docs/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminSettingsRoute = DocsAdminSettingsRouteImport.update({
  id: '/docs/admin/settings',
  path: '/docs/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminReportsRoute = DocsAdminReportsRouteImport.update({
  id: '/docs/admin/reports',
  path: '/docs/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminPaymentsRoute = DocsAdminPaymentsRouteImport.update({
  id: '/docs/admin/payments',
  path: '/docs/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminMembershipsRoute = DocsAdminMembershipsRouteImport.update({
  id: '/docs/admin/memberships',
  path: '/docs/admin/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminMembersRoute = DocsAdminMembersRouteImport.update({
  id: '/docs/admin/members',
  path: '/docs/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminEventsRoute = DocsAdminEventsRouteImport.update({
  id: '/docs/admin/events',
  path: '/docs/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminDashboardRoute = DocsAdminDashboardRouteImport.update({
  id: '/docs/admin/dashboard',
  path: '/docs/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminContentRoute = DocsAdminContentRouteImport.update({
  id: '/docs/admin/content',
  path: '/docs/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminAwardsRoute = DocsAdminAwardsRouteImport.update({
  id: '/docs/admin/awards',
  path: '/docs/admin/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesConferenceIdTicketsRoute =
  ConferencesConferenceIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)
const ConferencesConferenceIdSponsorsRoute =
  ConferencesConferenceIdSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)
const ConferencesConferenceIdSpeakersRoute =
  ConferencesConferenceIdSpeakersRouteImport.update({
    id: '/speakers',
    path: '/speakers',
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)
const ConferencesConferenceIdProgramRoute =
  ConferencesConferenceIdProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)
const ConferencesConferenceIdGalleryRoute =
  ConferencesConferenceIdGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)
const ChaptersChapterIdNewsRoute = ChaptersChapterIdNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const ChaptersChapterIdGalleryRoute =
  ChaptersChapterIdGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => ChaptersChapterIdRoute,
  } as any)
const ChaptersChapterIdEventsRoute = ChaptersChapterIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const ChaptersChapterIdAwardsRoute = ChaptersChapterIdAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => ChaptersChapterIdRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEducationWebinarsRoute =
  AccountEducationWebinarsRouteImport.update({
    id: '/webinars',
    path: '/webinars',
    getParentRoute: () => AccountEducationRouteRoute,
  } as any)
const AccountEducationResourcesRoute =
  AccountEducationResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AccountEducationRouteRoute,
  } as any)
const AccountEducationCpdRoute = AccountEducationCpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => AccountEducationRouteRoute,
} as any)
const DocsArchitectureServicesIndexRoute =
  DocsArchitectureServicesIndexRouteImport.update({
    id: '/docs/architecture/services/',
    path: '/docs/architecture/services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsArchitectureServicesShopifyRoute =
  DocsArchitectureServicesShopifyRouteImport.update({
    id: '/docs/architecture/services/shopify',
    path: '/docs/architecture/services/shopify',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsArchitectureServicesSanityRoute =
  DocsArchitectureServicesSanityRouteImport.update({
    id: '/docs/architecture/services/sanity',
    path: '/docs/architecture/services/sanity',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsArchitectureServicesKlaviyoRoute =
  DocsArchitectureServicesKlaviyoRouteImport.update({
    id: '/docs/architecture/services/klaviyo',
    path: '/docs/architecture/services/klaviyo',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsArchitectureServicesAuth0Route =
  DocsArchitectureServicesAuth0RouteImport.update({
    id: '/docs/architecture/services/auth0',
    path: '/docs/architecture/services/auth0',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsArchitectureServicesAlgoliaRoute =
  DocsArchitectureServicesAlgoliaRouteImport.update({
    id: '/docs/architecture/services/algolia',
    path: '/docs/architecture/services/algolia',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRouteWithChildren
  '/store': typeof StoreRoute
  '/account/education': typeof AccountEducationRouteRouteWithChildren
  '/account/awards': typeof AccountAwardsRoute
  '/account/events': typeof AccountEventsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRouteWithChildren
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/news': typeof ChaptersNewsRoute
  '/conferences/$conferenceId': typeof ConferencesConferenceIdRouteWithChildren
  '/docs/contents': typeof DocsContentsRoute
  '/docs/process': typeof DocsProcessRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/studio/awards': typeof StudioAwardsRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/customers': typeof StudioCustomersRoute
  '/studio/events': typeof StudioEventsRoute
  '/studio/news': typeof StudioNewsRoute
  '/studio/orders': typeof StudioOrdersRoute
  '/studio/pages': typeof StudioPagesRoute
  '/studio/products': typeof StudioProductsRoute
  '/account/': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/chapters': typeof ChaptersIndexRoute
  '/conferences': typeof ConferencesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/studio': typeof StudioIndexRoute
  '/account/education/cpd': typeof AccountEducationCpdRoute
  '/account/education/resources': typeof AccountEducationResourcesRoute
  '/account/education/webinars': typeof AccountEducationWebinarsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chapters/$chapterId/awards': typeof ChaptersChapterIdAwardsRoute
  '/chapters/$chapterId/events': typeof ChaptersChapterIdEventsRoute
  '/chapters/$chapterId/gallery': typeof ChaptersChapterIdGalleryRoute
  '/chapters/$chapterId/news': typeof ChaptersChapterIdNewsRoute
  '/conferences/$conferenceId/gallery': typeof ConferencesConferenceIdGalleryRoute
  '/conferences/$conferenceId/program': typeof ConferencesConferenceIdProgramRoute
  '/conferences/$conferenceId/speakers': typeof ConferencesConferenceIdSpeakersRoute
  '/conferences/$conferenceId/sponsors': typeof ConferencesConferenceIdSponsorsRoute
  '/conferences/$conferenceId/tickets': typeof ConferencesConferenceIdTicketsRoute
  '/docs/admin/awards': typeof DocsAdminAwardsRoute
  '/docs/admin/content': typeof DocsAdminContentRoute
  '/docs/admin/dashboard': typeof DocsAdminDashboardRoute
  '/docs/admin/events': typeof DocsAdminEventsRoute
  '/docs/admin/members': typeof DocsAdminMembersRoute
  '/docs/admin/memberships': typeof DocsAdminMembershipsRoute
  '/docs/admin/payments': typeof DocsAdminPaymentsRoute
  '/docs/admin/reports': typeof DocsAdminReportsRoute
  '/docs/admin/settings': typeof DocsAdminSettingsRoute
  '/docs/admin/submissions': typeof DocsAdminSubmissionsRoute
  '/docs/admin/support': typeof DocsAdminSupportRoute
  '/docs/appendix/wordpress': typeof DocsAppendixWordpressRoute
  '/docs/architecture/sitemap': typeof DocsArchitectureSitemapRoute
  '/docs/guidance/phases': typeof DocsGuidancePhasesRoute
  '/docs/guidance/priorities': typeof DocsGuidancePrioritiesRoute
  '/docs/overview/reverse-brief': typeof DocsOverviewReverseBriefRoute
  '/docs/studio/awards': typeof DocsStudioAwardsRoute
  '/docs/studio/collections': typeof DocsStudioCollectionsRoute
  '/docs/studio/customers': typeof DocsStudioCustomersRoute
  '/docs/studio/events': typeof DocsStudioEventsRoute
  '/docs/studio/news': typeof DocsStudioNewsRoute
  '/docs/studio/orders': typeof DocsStudioOrdersRoute
  '/docs/studio/pages': typeof DocsStudioPagesRoute
  '/docs/studio/products': typeof DocsStudioProductsRoute
  '/docs/vendor/brief': typeof DocsVendorBriefRoute
  '/account/education/': typeof AccountEducationIndexRoute
  '/chapters/$chapterId/': typeof ChaptersChapterIdIndexRoute
  '/conferences/$conferenceId/': typeof ConferencesConferenceIdIndexRoute
  '/docs/admin': typeof DocsAdminIndexRoute
  '/docs/appendix': typeof DocsAppendixIndexRoute
  '/docs/architecture': typeof DocsArchitectureIndexRoute
  '/docs/guidance': typeof DocsGuidanceIndexRoute
  '/docs/studio': typeof DocsStudioIndexRoute
  '/docs/vendor': typeof DocsVendorIndexRoute
  '/docs/architecture/services/algolia': typeof DocsArchitectureServicesAlgoliaRoute
  '/docs/architecture/services/auth0': typeof DocsArchitectureServicesAuth0Route
  '/docs/architecture/services/klaviyo': typeof DocsArchitectureServicesKlaviyoRoute
  '/docs/architecture/services/sanity': typeof DocsArchitectureServicesSanityRoute
  '/docs/architecture/services/shopify': typeof DocsArchitectureServicesShopifyRoute
  '/docs/architecture/services': typeof DocsArchitectureServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRouteWithChildren
  '/store': typeof StoreRoute
  '/account/awards': typeof AccountAwardsRoute
  '/account/events': typeof AccountEventsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/news': typeof ChaptersNewsRoute
  '/docs/contents': typeof DocsContentsRoute
  '/docs/process': typeof DocsProcessRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/studio/awards': typeof StudioAwardsRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/customers': typeof StudioCustomersRoute
  '/studio/events': typeof StudioEventsRoute
  '/studio/news': typeof StudioNewsRoute
  '/studio/orders': typeof StudioOrdersRoute
  '/studio/pages': typeof StudioPagesRoute
  '/studio/products': typeof StudioProductsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/chapters': typeof ChaptersIndexRoute
  '/conferences': typeof ConferencesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/studio': typeof StudioIndexRoute
  '/account/education/cpd': typeof AccountEducationCpdRoute
  '/account/education/resources': typeof AccountEducationResourcesRoute
  '/account/education/webinars': typeof AccountEducationWebinarsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chapters/$chapterId/awards': typeof ChaptersChapterIdAwardsRoute
  '/chapters/$chapterId/events': typeof ChaptersChapterIdEventsRoute
  '/chapters/$chapterId/gallery': typeof ChaptersChapterIdGalleryRoute
  '/chapters/$chapterId/news': typeof ChaptersChapterIdNewsRoute
  '/conferences/$conferenceId/gallery': typeof ConferencesConferenceIdGalleryRoute
  '/conferences/$conferenceId/program': typeof ConferencesConferenceIdProgramRoute
  '/conferences/$conferenceId/speakers': typeof ConferencesConferenceIdSpeakersRoute
  '/conferences/$conferenceId/sponsors': typeof ConferencesConferenceIdSponsorsRoute
  '/conferences/$conferenceId/tickets': typeof ConferencesConferenceIdTicketsRoute
  '/docs/admin/awards': typeof DocsAdminAwardsRoute
  '/docs/admin/content': typeof DocsAdminContentRoute
  '/docs/admin/dashboard': typeof DocsAdminDashboardRoute
  '/docs/admin/events': typeof DocsAdminEventsRoute
  '/docs/admin/members': typeof DocsAdminMembersRoute
  '/docs/admin/memberships': typeof DocsAdminMembershipsRoute
  '/docs/admin/payments': typeof DocsAdminPaymentsRoute
  '/docs/admin/reports': typeof DocsAdminReportsRoute
  '/docs/admin/settings': typeof DocsAdminSettingsRoute
  '/docs/admin/submissions': typeof DocsAdminSubmissionsRoute
  '/docs/admin/support': typeof DocsAdminSupportRoute
  '/docs/appendix/wordpress': typeof DocsAppendixWordpressRoute
  '/docs/architecture/sitemap': typeof DocsArchitectureSitemapRoute
  '/docs/guidance/phases': typeof DocsGuidancePhasesRoute
  '/docs/guidance/priorities': typeof DocsGuidancePrioritiesRoute
  '/docs/overview/reverse-brief': typeof DocsOverviewReverseBriefRoute
  '/docs/studio/awards': typeof DocsStudioAwardsRoute
  '/docs/studio/collections': typeof DocsStudioCollectionsRoute
  '/docs/studio/customers': typeof DocsStudioCustomersRoute
  '/docs/studio/events': typeof DocsStudioEventsRoute
  '/docs/studio/news': typeof DocsStudioNewsRoute
  '/docs/studio/orders': typeof DocsStudioOrdersRoute
  '/docs/studio/pages': typeof DocsStudioPagesRoute
  '/docs/studio/products': typeof DocsStudioProductsRoute
  '/docs/vendor/brief': typeof DocsVendorBriefRoute
  '/account/education': typeof AccountEducationIndexRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdIndexRoute
  '/conferences/$conferenceId': typeof ConferencesConferenceIdIndexRoute
  '/docs/admin': typeof DocsAdminIndexRoute
  '/docs/appendix': typeof DocsAppendixIndexRoute
  '/docs/architecture': typeof DocsArchitectureIndexRoute
  '/docs/guidance': typeof DocsGuidanceIndexRoute
  '/docs/studio': typeof DocsStudioIndexRoute
  '/docs/vendor': typeof DocsVendorIndexRoute
  '/docs/architecture/services/algolia': typeof DocsArchitectureServicesAlgoliaRoute
  '/docs/architecture/services/auth0': typeof DocsArchitectureServicesAuth0Route
  '/docs/architecture/services/klaviyo': typeof DocsArchitectureServicesKlaviyoRoute
  '/docs/architecture/services/sanity': typeof DocsArchitectureServicesSanityRoute
  '/docs/architecture/services/shopify': typeof DocsArchitectureServicesShopifyRoute
  '/docs/architecture/services': typeof DocsArchitectureServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRouteWithChildren
  '/store': typeof StoreRoute
  '/account/education': typeof AccountEducationRouteRouteWithChildren
  '/account/awards': typeof AccountAwardsRoute
  '/account/events': typeof AccountEventsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRouteWithChildren
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/news': typeof ChaptersNewsRoute
  '/conferences/$conferenceId': typeof ConferencesConferenceIdRouteWithChildren
  '/docs/contents': typeof DocsContentsRoute
  '/docs/process': typeof DocsProcessRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/studio/awards': typeof StudioAwardsRoute
  '/studio/collections': typeof StudioCollectionsRoute
  '/studio/customers': typeof StudioCustomersRoute
  '/studio/events': typeof StudioEventsRoute
  '/studio/news': typeof StudioNewsRoute
  '/studio/orders': typeof StudioOrdersRoute
  '/studio/pages': typeof StudioPagesRoute
  '/studio/products': typeof StudioProductsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/conferences/': typeof ConferencesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/account/education/cpd': typeof AccountEducationCpdRoute
  '/account/education/resources': typeof AccountEducationResourcesRoute
  '/account/education/webinars': typeof AccountEducationWebinarsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chapters/$chapterId/awards': typeof ChaptersChapterIdAwardsRoute
  '/chapters/$chapterId/events': typeof ChaptersChapterIdEventsRoute
  '/chapters/$chapterId/gallery': typeof ChaptersChapterIdGalleryRoute
  '/chapters/$chapterId/news': typeof ChaptersChapterIdNewsRoute
  '/conferences/$conferenceId/gallery': typeof ConferencesConferenceIdGalleryRoute
  '/conferences/$conferenceId/program': typeof ConferencesConferenceIdProgramRoute
  '/conferences/$conferenceId/speakers': typeof ConferencesConferenceIdSpeakersRoute
  '/conferences/$conferenceId/sponsors': typeof ConferencesConferenceIdSponsorsRoute
  '/conferences/$conferenceId/tickets': typeof ConferencesConferenceIdTicketsRoute
  '/docs/admin/awards': typeof DocsAdminAwardsRoute
  '/docs/admin/content': typeof DocsAdminContentRoute
  '/docs/admin/dashboard': typeof DocsAdminDashboardRoute
  '/docs/admin/events': typeof DocsAdminEventsRoute
  '/docs/admin/members': typeof DocsAdminMembersRoute
  '/docs/admin/memberships': typeof DocsAdminMembershipsRoute
  '/docs/admin/payments': typeof DocsAdminPaymentsRoute
  '/docs/admin/reports': typeof DocsAdminReportsRoute
  '/docs/admin/settings': typeof DocsAdminSettingsRoute
  '/docs/admin/submissions': typeof DocsAdminSubmissionsRoute
  '/docs/admin/support': typeof DocsAdminSupportRoute
  '/docs/appendix/wordpress': typeof DocsAppendixWordpressRoute
  '/docs/architecture/sitemap': typeof DocsArchitectureSitemapRoute
  '/docs/guidance/phases': typeof DocsGuidancePhasesRoute
  '/docs/guidance/priorities': typeof DocsGuidancePrioritiesRoute
  '/docs/overview/reverse-brief': typeof DocsOverviewReverseBriefRoute
  '/docs/studio/awards': typeof DocsStudioAwardsRoute
  '/docs/studio/collections': typeof DocsStudioCollectionsRoute
  '/docs/studio/customers': typeof DocsStudioCustomersRoute
  '/docs/studio/events': typeof DocsStudioEventsRoute
  '/docs/studio/news': typeof DocsStudioNewsRoute
  '/docs/studio/orders': typeof DocsStudioOrdersRoute
  '/docs/studio/pages': typeof DocsStudioPagesRoute
  '/docs/studio/products': typeof DocsStudioProductsRoute
  '/docs/vendor/brief': typeof DocsVendorBriefRoute
  '/account/education/': typeof AccountEducationIndexRoute
  '/chapters/$chapterId/': typeof ChaptersChapterIdIndexRoute
  '/conferences/$conferenceId/': typeof ConferencesConferenceIdIndexRoute
  '/docs/admin/': typeof DocsAdminIndexRoute
  '/docs/appendix/': typeof DocsAppendixIndexRoute
  '/docs/architecture/': typeof DocsArchitectureIndexRoute
  '/docs/guidance/': typeof DocsGuidanceIndexRoute
  '/docs/studio/': typeof DocsStudioIndexRoute
  '/docs/vendor/': typeof DocsVendorIndexRoute
  '/docs/architecture/services/algolia': typeof DocsArchitectureServicesAlgoliaRoute
  '/docs/architecture/services/auth0': typeof DocsArchitectureServicesAuth0Route
  '/docs/architecture/services/klaviyo': typeof DocsArchitectureServicesKlaviyoRoute
  '/docs/architecture/services/sanity': typeof DocsArchitectureServicesSanityRoute
  '/docs/architecture/services/shopify': typeof DocsArchitectureServicesShopifyRoute
  '/docs/architecture/services/': typeof DocsArchitectureServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/resources'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/contact'
    | '/events'
    | '/news'
    | '/store'
    | '/account/education'
    | '/account/awards'
    | '/account/events'
    | '/account/invoices'
    | '/account/login'
    | '/account/profile'
    | '/account/subscription'
    | '/account/upgrade'
    | '/admin/awards'
    | '/admin/content'
    | '/admin/events'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/chapters/$chapterId'
    | '/chapters/events'
    | '/chapters/news'
    | '/conferences/$conferenceId'
    | '/docs/contents'
    | '/docs/process'
    | '/news/$slug'
    | '/pages/$pageId'
    | '/resources/$resourceId'
    | '/studio/awards'
    | '/studio/collections'
    | '/studio/customers'
    | '/studio/events'
    | '/studio/news'
    | '/studio/orders'
    | '/studio/pages'
    | '/studio/products'
    | '/account/'
    | '/admin'
    | '/chapters'
    | '/conferences'
    | '/docs'
    | '/resources/'
    | '/studio'
    | '/account/education/cpd'
    | '/account/education/resources'
    | '/account/education/webinars'
    | '/api/trpc/$'
    | '/chapters/$chapterId/awards'
    | '/chapters/$chapterId/events'
    | '/chapters/$chapterId/gallery'
    | '/chapters/$chapterId/news'
    | '/conferences/$conferenceId/gallery'
    | '/conferences/$conferenceId/program'
    | '/conferences/$conferenceId/speakers'
    | '/conferences/$conferenceId/sponsors'
    | '/conferences/$conferenceId/tickets'
    | '/docs/admin/awards'
    | '/docs/admin/content'
    | '/docs/admin/dashboard'
    | '/docs/admin/events'
    | '/docs/admin/members'
    | '/docs/admin/memberships'
    | '/docs/admin/payments'
    | '/docs/admin/reports'
    | '/docs/admin/settings'
    | '/docs/admin/submissions'
    | '/docs/admin/support'
    | '/docs/appendix/wordpress'
    | '/docs/architecture/sitemap'
    | '/docs/guidance/phases'
    | '/docs/guidance/priorities'
    | '/docs/overview/reverse-brief'
    | '/docs/studio/awards'
    | '/docs/studio/collections'
    | '/docs/studio/customers'
    | '/docs/studio/events'
    | '/docs/studio/news'
    | '/docs/studio/orders'
    | '/docs/studio/pages'
    | '/docs/studio/products'
    | '/docs/vendor/brief'
    | '/account/education/'
    | '/chapters/$chapterId/'
    | '/conferences/$conferenceId/'
    | '/docs/admin'
    | '/docs/appendix'
    | '/docs/architecture'
    | '/docs/guidance'
    | '/docs/studio'
    | '/docs/vendor'
    | '/docs/architecture/services/algolia'
    | '/docs/architecture/services/auth0'
    | '/docs/architecture/services/klaviyo'
    | '/docs/architecture/services/sanity'
    | '/docs/architecture/services/shopify'
    | '/docs/architecture/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/contact'
    | '/events'
    | '/news'
    | '/store'
    | '/account/awards'
    | '/account/events'
    | '/account/invoices'
    | '/account/login'
    | '/account/profile'
    | '/account/subscription'
    | '/account/upgrade'
    | '/admin/awards'
    | '/admin/content'
    | '/admin/events'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/chapters/events'
    | '/chapters/news'
    | '/docs/contents'
    | '/docs/process'
    | '/news/$slug'
    | '/pages/$pageId'
    | '/resources/$resourceId'
    | '/studio/awards'
    | '/studio/collections'
    | '/studio/customers'
    | '/studio/events'
    | '/studio/news'
    | '/studio/orders'
    | '/studio/pages'
    | '/studio/products'
    | '/account'
    | '/admin'
    | '/chapters'
    | '/conferences'
    | '/docs'
    | '/resources'
    | '/studio'
    | '/account/education/cpd'
    | '/account/education/resources'
    | '/account/education/webinars'
    | '/api/trpc/$'
    | '/chapters/$chapterId/awards'
    | '/chapters/$chapterId/events'
    | '/chapters/$chapterId/gallery'
    | '/chapters/$chapterId/news'
    | '/conferences/$conferenceId/gallery'
    | '/conferences/$conferenceId/program'
    | '/conferences/$conferenceId/speakers'
    | '/conferences/$conferenceId/sponsors'
    | '/conferences/$conferenceId/tickets'
    | '/docs/admin/awards'
    | '/docs/admin/content'
    | '/docs/admin/dashboard'
    | '/docs/admin/events'
    | '/docs/admin/members'
    | '/docs/admin/memberships'
    | '/docs/admin/payments'
    | '/docs/admin/reports'
    | '/docs/admin/settings'
    | '/docs/admin/submissions'
    | '/docs/admin/support'
    | '/docs/appendix/wordpress'
    | '/docs/architecture/sitemap'
    | '/docs/guidance/phases'
    | '/docs/guidance/priorities'
    | '/docs/overview/reverse-brief'
    | '/docs/studio/awards'
    | '/docs/studio/collections'
    | '/docs/studio/customers'
    | '/docs/studio/events'
    | '/docs/studio/news'
    | '/docs/studio/orders'
    | '/docs/studio/pages'
    | '/docs/studio/products'
    | '/docs/vendor/brief'
    | '/account/education'
    | '/chapters/$chapterId'
    | '/conferences/$conferenceId'
    | '/docs/admin'
    | '/docs/appendix'
    | '/docs/architecture'
    | '/docs/guidance'
    | '/docs/studio'
    | '/docs/vendor'
    | '/docs/architecture/services/algolia'
    | '/docs/architecture/services/auth0'
    | '/docs/architecture/services/klaviyo'
    | '/docs/architecture/services/sanity'
    | '/docs/architecture/services/shopify'
    | '/docs/architecture/services'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/resources'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/contact'
    | '/events'
    | '/news'
    | '/store'
    | '/account/education'
    | '/account/awards'
    | '/account/events'
    | '/account/invoices'
    | '/account/login'
    | '/account/profile'
    | '/account/subscription'
    | '/account/upgrade'
    | '/admin/awards'
    | '/admin/content'
    | '/admin/events'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/support'
    | '/chapters/$chapterId'
    | '/chapters/events'
    | '/chapters/news'
    | '/conferences/$conferenceId'
    | '/docs/contents'
    | '/docs/process'
    | '/news/$slug'
    | '/pages/$pageId'
    | '/resources/$resourceId'
    | '/studio/awards'
    | '/studio/collections'
    | '/studio/customers'
    | '/studio/events'
    | '/studio/news'
    | '/studio/orders'
    | '/studio/pages'
    | '/studio/products'
    | '/account/'
    | '/admin/'
    | '/chapters/'
    | '/conferences/'
    | '/docs/'
    | '/resources/'
    | '/studio/'
    | '/account/education/cpd'
    | '/account/education/resources'
    | '/account/education/webinars'
    | '/api/trpc/$'
    | '/chapters/$chapterId/awards'
    | '/chapters/$chapterId/events'
    | '/chapters/$chapterId/gallery'
    | '/chapters/$chapterId/news'
    | '/conferences/$conferenceId/gallery'
    | '/conferences/$conferenceId/program'
    | '/conferences/$conferenceId/speakers'
    | '/conferences/$conferenceId/sponsors'
    | '/conferences/$conferenceId/tickets'
    | '/docs/admin/awards'
    | '/docs/admin/content'
    | '/docs/admin/dashboard'
    | '/docs/admin/events'
    | '/docs/admin/members'
    | '/docs/admin/memberships'
    | '/docs/admin/payments'
    | '/docs/admin/reports'
    | '/docs/admin/settings'
    | '/docs/admin/submissions'
    | '/docs/admin/support'
    | '/docs/appendix/wordpress'
    | '/docs/architecture/sitemap'
    | '/docs/guidance/phases'
    | '/docs/guidance/priorities'
    | '/docs/overview/reverse-brief'
    | '/docs/studio/awards'
    | '/docs/studio/collections'
    | '/docs/studio/customers'
    | '/docs/studio/events'
    | '/docs/studio/news'
    | '/docs/studio/orders'
    | '/docs/studio/pages'
    | '/docs/studio/products'
    | '/docs/vendor/brief'
    | '/account/education/'
    | '/chapters/$chapterId/'
    | '/conferences/$conferenceId/'
    | '/docs/admin/'
    | '/docs/appendix/'
    | '/docs/architecture/'
    | '/docs/guidance/'
    | '/docs/studio/'
    | '/docs/vendor/'
    | '/docs/architecture/services/algolia'
    | '/docs/architecture/services/auth0'
    | '/docs/architecture/services/klaviyo'
    | '/docs/architecture/services/sanity'
    | '/docs/architecture/services/shopify'
    | '/docs/architecture/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  ResourcesRouteRoute: typeof ResourcesRouteRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  CalendarRoute: typeof CalendarRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  NewsRoute: typeof NewsRouteWithChildren
  StoreRoute: typeof StoreRoute
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRouteWithChildren
  ChaptersEventsRoute: typeof ChaptersEventsRoute
  ChaptersNewsRoute: typeof ChaptersNewsRoute
  ConferencesConferenceIdRoute: typeof ConferencesConferenceIdRouteWithChildren
  DocsContentsRoute: typeof DocsContentsRoute
  DocsProcessRoute: typeof DocsProcessRoute
  PagesPageIdRoute: typeof PagesPageIdRoute
  StudioAwardsRoute: typeof StudioAwardsRoute
  StudioCollectionsRoute: typeof StudioCollectionsRoute
  StudioCustomersRoute: typeof StudioCustomersRoute
  StudioEventsRoute: typeof StudioEventsRoute
  StudioNewsRoute: typeof StudioNewsRoute
  StudioOrdersRoute: typeof StudioOrdersRoute
  StudioPagesRoute: typeof StudioPagesRoute
  StudioProductsRoute: typeof StudioProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
  ConferencesIndexRoute: typeof ConferencesIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DocsAdminAwardsRoute: typeof DocsAdminAwardsRoute
  DocsAdminContentRoute: typeof DocsAdminContentRoute
  DocsAdminDashboardRoute: typeof DocsAdminDashboardRoute
  DocsAdminEventsRoute: typeof DocsAdminEventsRoute
  DocsAdminMembersRoute: typeof DocsAdminMembersRoute
  DocsAdminMembershipsRoute: typeof DocsAdminMembershipsRoute
  DocsAdminPaymentsRoute: typeof DocsAdminPaymentsRoute
  DocsAdminReportsRoute: typeof DocsAdminReportsRoute
  DocsAdminSettingsRoute: typeof DocsAdminSettingsRoute
  DocsAdminSubmissionsRoute: typeof DocsAdminSubmissionsRoute
  DocsAdminSupportRoute: typeof DocsAdminSupportRoute
  DocsAppendixWordpressRoute: typeof DocsAppendixWordpressRoute
  DocsArchitectureSitemapRoute: typeof DocsArchitectureSitemapRoute
  DocsGuidancePhasesRoute: typeof DocsGuidancePhasesRoute
  DocsGuidancePrioritiesRoute: typeof DocsGuidancePrioritiesRoute
  DocsOverviewReverseBriefRoute: typeof DocsOverviewReverseBriefRoute
  DocsStudioAwardsRoute: typeof DocsStudioAwardsRoute
  DocsStudioCollectionsRoute: typeof DocsStudioCollectionsRoute
  DocsStudioCustomersRoute: typeof DocsStudioCustomersRoute
  DocsStudioEventsRoute: typeof DocsStudioEventsRoute
  DocsStudioNewsRoute: typeof DocsStudioNewsRoute
  DocsStudioOrdersRoute: typeof DocsStudioOrdersRoute
  DocsStudioPagesRoute: typeof DocsStudioPagesRoute
  DocsStudioProductsRoute: typeof DocsStudioProductsRoute
  DocsVendorBriefRoute: typeof DocsVendorBriefRoute
  DocsAdminIndexRoute: typeof DocsAdminIndexRoute
  DocsAppendixIndexRoute: typeof DocsAppendixIndexRoute
  DocsArchitectureIndexRoute: typeof DocsArchitectureIndexRoute
  DocsGuidanceIndexRoute: typeof DocsGuidanceIndexRoute
  DocsStudioIndexRoute: typeof DocsStudioIndexRoute
  DocsVendorIndexRoute: typeof DocsVendorIndexRoute
  DocsArchitectureServicesAlgoliaRoute: typeof DocsArchitectureServicesAlgoliaRoute
  DocsArchitectureServicesAuth0Route: typeof DocsArchitectureServicesAuth0Route
  DocsArchitectureServicesKlaviyoRoute: typeof DocsArchitectureServicesKlaviyoRoute
  DocsArchitectureServicesSanityRoute: typeof DocsArchitectureServicesSanityRoute
  DocsArchitectureServicesShopifyRoute: typeof DocsArchitectureServicesShopifyRoute
  DocsArchitectureServicesIndexRoute: typeof DocsArchitectureServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences/': {
      id: '/conferences/'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/studio/products': {
      id: '/studio/products'
      path: '/studio/products'
      fullPath: '/studio/products'
      preLoaderRoute: typeof StudioProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/pages': {
      id: '/studio/pages'
      path: '/studio/pages'
      fullPath: '/studio/pages'
      preLoaderRoute: typeof StudioPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/orders': {
      id: '/studio/orders'
      path: '/studio/orders'
      fullPath: '/studio/orders'
      preLoaderRoute: typeof StudioOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/news': {
      id: '/studio/news'
      path: '/studio/news'
      fullPath: '/studio/news'
      preLoaderRoute: typeof StudioNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/events': {
      id: '/studio/events'
      path: '/studio/events'
      fullPath: '/studio/events'
      preLoaderRoute: typeof StudioEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/customers': {
      id: '/studio/customers'
      path: '/studio/customers'
      fullPath: '/studio/customers'
      preLoaderRoute: typeof StudioCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/collections': {
      id: '/studio/collections'
      path: '/studio/collections'
      fullPath: '/studio/collections'
      preLoaderRoute: typeof StudioCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/awards': {
      id: '/studio/awards'
      path: '/studio/awards'
      fullPath: '/studio/awards'
      preLoaderRoute: typeof StudioAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$resourceId': {
      id: '/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof ResourcesResourceIdRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/docs/process': {
      id: '/docs/process'
      path: '/docs/process'
      fullPath: '/docs/process'
      preLoaderRoute: typeof DocsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/contents': {
      id: '/docs/contents'
      path: '/docs/contents'
      fullPath: '/docs/contents'
      preLoaderRoute: typeof DocsContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences/$conferenceId': {
      id: '/conferences/$conferenceId'
      path: '/conferences/$conferenceId'
      fullPath: '/conferences/$conferenceId'
      preLoaderRoute: typeof ConferencesConferenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/news': {
      id: '/chapters/news'
      path: '/chapters/news'
      fullPath: '/chapters/news'
      preLoaderRoute: typeof ChaptersNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/events': {
      id: '/chapters/events'
      path: '/chapters/events'
      fullPath: '/chapters/events'
      preLoaderRoute: typeof ChaptersEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/admin/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/admin/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/upgrade': {
      id: '/account/upgrade'
      path: '/upgrade'
      fullPath: '/account/upgrade'
      preLoaderRoute: typeof AccountUpgradeRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/subscription': {
      id: '/account/subscription'
      path: '/subscription'
      fullPath: '/account/subscription'
      preLoaderRoute: typeof AccountSubscriptionRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/invoices': {
      id: '/account/invoices'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AccountInvoicesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/events': {
      id: '/account/events'
      path: '/events'
      fullPath: '/account/events'
      preLoaderRoute: typeof AccountEventsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/awards': {
      id: '/account/awards'
      path: '/awards'
      fullPath: '/account/awards'
      preLoaderRoute: typeof AccountAwardsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/education': {
      id: '/account/education'
      path: '/education'
      fullPath: '/account/education'
      preLoaderRoute: typeof AccountEducationRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/docs/vendor/': {
      id: '/docs/vendor/'
      path: '/docs/vendor'
      fullPath: '/docs/vendor'
      preLoaderRoute: typeof DocsVendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/': {
      id: '/docs/studio/'
      path: '/docs/studio'
      fullPath: '/docs/studio'
      preLoaderRoute: typeof DocsStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guidance/': {
      id: '/docs/guidance/'
      path: '/docs/guidance'
      fullPath: '/docs/guidance'
      preLoaderRoute: typeof DocsGuidanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/': {
      id: '/docs/architecture/'
      path: '/docs/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/appendix/': {
      id: '/docs/appendix/'
      path: '/docs/appendix'
      fullPath: '/docs/appendix'
      preLoaderRoute: typeof DocsAppendixIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/': {
      id: '/docs/admin/'
      path: '/docs/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocsAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences/$conferenceId/': {
      id: '/conferences/$conferenceId/'
      path: '/'
      fullPath: '/conferences/$conferenceId/'
      preLoaderRoute: typeof ConferencesConferenceIdIndexRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
    '/chapters/$chapterId/': {
      id: '/chapters/$chapterId/'
      path: '/'
      fullPath: '/chapters/$chapterId/'
      preLoaderRoute: typeof ChaptersChapterIdIndexRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/account/education/': {
      id: '/account/education/'
      path: '/'
      fullPath: '/account/education/'
      preLoaderRoute: typeof AccountEducationIndexRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
    '/docs/vendor/brief': {
      id: '/docs/vendor/brief'
      path: '/docs/vendor/brief'
      fullPath: '/docs/vendor/brief'
      preLoaderRoute: typeof DocsVendorBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/products': {
      id: '/docs/studio/products'
      path: '/docs/studio/products'
      fullPath: '/docs/studio/products'
      preLoaderRoute: typeof DocsStudioProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/pages': {
      id: '/docs/studio/pages'
      path: '/docs/studio/pages'
      fullPath: '/docs/studio/pages'
      preLoaderRoute: typeof DocsStudioPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/orders': {
      id: '/docs/studio/orders'
      path: '/docs/studio/orders'
      fullPath: '/docs/studio/orders'
      preLoaderRoute: typeof DocsStudioOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/news': {
      id: '/docs/studio/news'
      path: '/docs/studio/news'
      fullPath: '/docs/studio/news'
      preLoaderRoute: typeof DocsStudioNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/events': {
      id: '/docs/studio/events'
      path: '/docs/studio/events'
      fullPath: '/docs/studio/events'
      preLoaderRoute: typeof DocsStudioEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/customers': {
      id: '/docs/studio/customers'
      path: '/docs/studio/customers'
      fullPath: '/docs/studio/customers'
      preLoaderRoute: typeof DocsStudioCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/collections': {
      id: '/docs/studio/collections'
      path: '/docs/studio/collections'
      fullPath: '/docs/studio/collections'
      preLoaderRoute: typeof DocsStudioCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/studio/awards': {
      id: '/docs/studio/awards'
      path: '/docs/studio/awards'
      fullPath: '/docs/studio/awards'
      preLoaderRoute: typeof DocsStudioAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/overview/reverse-brief': {
      id: '/docs/overview/reverse-brief'
      path: '/docs/overview/reverse-brief'
      fullPath: '/docs/overview/reverse-brief'
      preLoaderRoute: typeof DocsOverviewReverseBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guidance/priorities': {
      id: '/docs/guidance/priorities'
      path: '/docs/guidance/priorities'
      fullPath: '/docs/guidance/priorities'
      preLoaderRoute: typeof DocsGuidancePrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guidance/phases': {
      id: '/docs/guidance/phases'
      path: '/docs/guidance/phases'
      fullPath: '/docs/guidance/phases'
      preLoaderRoute: typeof DocsGuidancePhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/sitemap': {
      id: '/docs/architecture/sitemap'
      path: '/docs/architecture/sitemap'
      fullPath: '/docs/architecture/sitemap'
      preLoaderRoute: typeof DocsArchitectureSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/appendix/wordpress': {
      id: '/docs/appendix/wordpress'
      path: '/docs/appendix/wordpress'
      fullPath: '/docs/appendix/wordpress'
      preLoaderRoute: typeof DocsAppendixWordpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/support': {
      id: '/docs/admin/support'
      path: '/docs/admin/support'
      fullPath: '/docs/admin/support'
      preLoaderRoute: typeof DocsAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/submissions': {
      id: '/docs/admin/submissions'
      path: '/docs/admin/submissions'
      fullPath: '/docs/admin/submissions'
      preLoaderRoute: typeof DocsAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/settings': {
      id: '/docs/admin/settings'
      path: '/docs/admin/settings'
      fullPath: '/docs/admin/settings'
      preLoaderRoute: typeof DocsAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/reports': {
      id: '/docs/admin/reports'
      path: '/docs/admin/reports'
      fullPath: '/docs/admin/reports'
      preLoaderRoute: typeof DocsAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/payments': {
      id: '/docs/admin/payments'
      path: '/docs/admin/payments'
      fullPath: '/docs/admin/payments'
      preLoaderRoute: typeof DocsAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/memberships': {
      id: '/docs/admin/memberships'
      path: '/docs/admin/memberships'
      fullPath: '/docs/admin/memberships'
      preLoaderRoute: typeof DocsAdminMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/members': {
      id: '/docs/admin/members'
      path: '/docs/admin/members'
      fullPath: '/docs/admin/members'
      preLoaderRoute: typeof DocsAdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/events': {
      id: '/docs/admin/events'
      path: '/docs/admin/events'
      fullPath: '/docs/admin/events'
      preLoaderRoute: typeof DocsAdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/dashboard': {
      id: '/docs/admin/dashboard'
      path: '/docs/admin/dashboard'
      fullPath: '/docs/admin/dashboard'
      preLoaderRoute: typeof DocsAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/content': {
      id: '/docs/admin/content'
      path: '/docs/admin/content'
      fullPath: '/docs/admin/content'
      preLoaderRoute: typeof DocsAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin/awards': {
      id: '/docs/admin/awards'
      path: '/docs/admin/awards'
      fullPath: '/docs/admin/awards'
      preLoaderRoute: typeof DocsAdminAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences/$conferenceId/tickets': {
      id: '/conferences/$conferenceId/tickets'
      path: '/tickets'
      fullPath: '/conferences/$conferenceId/tickets'
      preLoaderRoute: typeof ConferencesConferenceIdTicketsRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
    '/conferences/$conferenceId/sponsors': {
      id: '/conferences/$conferenceId/sponsors'
      path: '/sponsors'
      fullPath: '/conferences/$conferenceId/sponsors'
      preLoaderRoute: typeof ConferencesConferenceIdSponsorsRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
    '/conferences/$conferenceId/speakers': {
      id: '/conferences/$conferenceId/speakers'
      path: '/speakers'
      fullPath: '/conferences/$conferenceId/speakers'
      preLoaderRoute: typeof ConferencesConferenceIdSpeakersRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
    '/conferences/$conferenceId/program': {
      id: '/conferences/$conferenceId/program'
      path: '/program'
      fullPath: '/conferences/$conferenceId/program'
      preLoaderRoute: typeof ConferencesConferenceIdProgramRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
    '/conferences/$conferenceId/gallery': {
      id: '/conferences/$conferenceId/gallery'
      path: '/gallery'
      fullPath: '/conferences/$conferenceId/gallery'
      preLoaderRoute: typeof ConferencesConferenceIdGalleryRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
    '/chapters/$chapterId/news': {
      id: '/chapters/$chapterId/news'
      path: '/news'
      fullPath: '/chapters/$chapterId/news'
      preLoaderRoute: typeof ChaptersChapterIdNewsRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/chapters/$chapterId/gallery': {
      id: '/chapters/$chapterId/gallery'
      path: '/gallery'
      fullPath: '/chapters/$chapterId/gallery'
      preLoaderRoute: typeof ChaptersChapterIdGalleryRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/chapters/$chapterId/events': {
      id: '/chapters/$chapterId/events'
      path: '/events'
      fullPath: '/chapters/$chapterId/events'
      preLoaderRoute: typeof ChaptersChapterIdEventsRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/chapters/$chapterId/awards': {
      id: '/chapters/$chapterId/awards'
      path: '/awards'
      fullPath: '/chapters/$chapterId/awards'
      preLoaderRoute: typeof ChaptersChapterIdAwardsRouteImport
      parentRoute: typeof ChaptersChapterIdRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/education/webinars': {
      id: '/account/education/webinars'
      path: '/webinars'
      fullPath: '/account/education/webinars'
      preLoaderRoute: typeof AccountEducationWebinarsRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
    '/account/education/resources': {
      id: '/account/education/resources'
      path: '/resources'
      fullPath: '/account/education/resources'
      preLoaderRoute: typeof AccountEducationResourcesRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
    '/account/education/cpd': {
      id: '/account/education/cpd'
      path: '/cpd'
      fullPath: '/account/education/cpd'
      preLoaderRoute: typeof AccountEducationCpdRouteImport
      parentRoute: typeof AccountEducationRouteRoute
    }
    '/docs/architecture/services/': {
      id: '/docs/architecture/services/'
      path: '/docs/architecture/services'
      fullPath: '/docs/architecture/services'
      preLoaderRoute: typeof DocsArchitectureServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/services/shopify': {
      id: '/docs/architecture/services/shopify'
      path: '/docs/architecture/services/shopify'
      fullPath: '/docs/architecture/services/shopify'
      preLoaderRoute: typeof DocsArchitectureServicesShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/services/sanity': {
      id: '/docs/architecture/services/sanity'
      path: '/docs/architecture/services/sanity'
      fullPath: '/docs/architecture/services/sanity'
      preLoaderRoute: typeof DocsArchitectureServicesSanityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/services/klaviyo': {
      id: '/docs/architecture/services/klaviyo'
      path: '/docs/architecture/services/klaviyo'
      fullPath: '/docs/architecture/services/klaviyo'
      preLoaderRoute: typeof DocsArchitectureServicesKlaviyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/services/auth0': {
      id: '/docs/architecture/services/auth0'
      path: '/docs/architecture/services/auth0'
      fullPath: '/docs/architecture/services/auth0'
      preLoaderRoute: typeof DocsArchitectureServicesAuth0RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/services/algolia': {
      id: '/docs/architecture/services/algolia'
      path: '/docs/architecture/services/algolia'
      fullPath: '/docs/architecture/services/algolia'
      preLoaderRoute: typeof DocsArchitectureServicesAlgoliaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountEducationRouteRouteChildren {
  AccountEducationCpdRoute: typeof AccountEducationCpdRoute
  AccountEducationResourcesRoute: typeof AccountEducationResourcesRoute
  AccountEducationWebinarsRoute: typeof AccountEducationWebinarsRoute
  AccountEducationIndexRoute: typeof AccountEducationIndexRoute
}

const AccountEducationRouteRouteChildren: AccountEducationRouteRouteChildren = {
  AccountEducationCpdRoute: AccountEducationCpdRoute,
  AccountEducationResourcesRoute: AccountEducationResourcesRoute,
  AccountEducationWebinarsRoute: AccountEducationWebinarsRoute,
  AccountEducationIndexRoute: AccountEducationIndexRoute,
}

const AccountEducationRouteRouteWithChildren =
  AccountEducationRouteRoute._addFileChildren(
    AccountEducationRouteRouteChildren,
  )

interface AccountRouteRouteChildren {
  AccountEducationRouteRoute: typeof AccountEducationRouteRouteWithChildren
  AccountAwardsRoute: typeof AccountAwardsRoute
  AccountEventsRoute: typeof AccountEventsRoute
  AccountInvoicesRoute: typeof AccountInvoicesRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSubscriptionRoute: typeof AccountSubscriptionRoute
  AccountUpgradeRoute: typeof AccountUpgradeRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountEducationRouteRoute: AccountEducationRouteRouteWithChildren,
  AccountAwardsRoute: AccountAwardsRoute,
  AccountEventsRoute: AccountEventsRoute,
  AccountInvoicesRoute: AccountInvoicesRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSubscriptionRoute: AccountSubscriptionRoute,
  AccountUpgradeRoute: AccountUpgradeRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface ResourcesRouteRouteChildren {
  ResourcesResourceIdRoute: typeof ResourcesResourceIdRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteRouteChildren: ResourcesRouteRouteChildren = {
  ResourcesResourceIdRoute: ResourcesResourceIdRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteRouteWithChildren = ResourcesRouteRoute._addFileChildren(
  ResourcesRouteRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ChaptersChapterIdRouteChildren {
  ChaptersChapterIdAwardsRoute: typeof ChaptersChapterIdAwardsRoute
  ChaptersChapterIdEventsRoute: typeof ChaptersChapterIdEventsRoute
  ChaptersChapterIdGalleryRoute: typeof ChaptersChapterIdGalleryRoute
  ChaptersChapterIdNewsRoute: typeof ChaptersChapterIdNewsRoute
  ChaptersChapterIdIndexRoute: typeof ChaptersChapterIdIndexRoute
}

const ChaptersChapterIdRouteChildren: ChaptersChapterIdRouteChildren = {
  ChaptersChapterIdAwardsRoute: ChaptersChapterIdAwardsRoute,
  ChaptersChapterIdEventsRoute: ChaptersChapterIdEventsRoute,
  ChaptersChapterIdGalleryRoute: ChaptersChapterIdGalleryRoute,
  ChaptersChapterIdNewsRoute: ChaptersChapterIdNewsRoute,
  ChaptersChapterIdIndexRoute: ChaptersChapterIdIndexRoute,
}

const ChaptersChapterIdRouteWithChildren =
  ChaptersChapterIdRoute._addFileChildren(ChaptersChapterIdRouteChildren)

interface ConferencesConferenceIdRouteChildren {
  ConferencesConferenceIdGalleryRoute: typeof ConferencesConferenceIdGalleryRoute
  ConferencesConferenceIdProgramRoute: typeof ConferencesConferenceIdProgramRoute
  ConferencesConferenceIdSpeakersRoute: typeof ConferencesConferenceIdSpeakersRoute
  ConferencesConferenceIdSponsorsRoute: typeof ConferencesConferenceIdSponsorsRoute
  ConferencesConferenceIdTicketsRoute: typeof ConferencesConferenceIdTicketsRoute
  ConferencesConferenceIdIndexRoute: typeof ConferencesConferenceIdIndexRoute
}

const ConferencesConferenceIdRouteChildren: ConferencesConferenceIdRouteChildren =
  {
    ConferencesConferenceIdGalleryRoute: ConferencesConferenceIdGalleryRoute,
    ConferencesConferenceIdProgramRoute: ConferencesConferenceIdProgramRoute,
    ConferencesConferenceIdSpeakersRoute: ConferencesConferenceIdSpeakersRoute,
    ConferencesConferenceIdSponsorsRoute: ConferencesConferenceIdSponsorsRoute,
    ConferencesConferenceIdTicketsRoute: ConferencesConferenceIdTicketsRoute,
    ConferencesConferenceIdIndexRoute: ConferencesConferenceIdIndexRoute,
  }

const ConferencesConferenceIdRouteWithChildren =
  ConferencesConferenceIdRoute._addFileChildren(
    ConferencesConferenceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  ResourcesRouteRoute: ResourcesRouteRouteWithChildren,
  AwardsRoute: AwardsRoute,
  CalendarRoute: CalendarRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  NewsRoute: NewsRouteWithChildren,
  StoreRoute: StoreRoute,
  AdminAwardsRoute: AdminAwardsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRouteWithChildren,
  ChaptersEventsRoute: ChaptersEventsRoute,
  ChaptersNewsRoute: ChaptersNewsRoute,
  ConferencesConferenceIdRoute: ConferencesConferenceIdRouteWithChildren,
  DocsContentsRoute: DocsContentsRoute,
  DocsProcessRoute: DocsProcessRoute,
  PagesPageIdRoute: PagesPageIdRoute,
  StudioAwardsRoute: StudioAwardsRoute,
  StudioCollectionsRoute: StudioCollectionsRoute,
  StudioCustomersRoute: StudioCustomersRoute,
  StudioEventsRoute: StudioEventsRoute,
  StudioNewsRoute: StudioNewsRoute,
  StudioOrdersRoute: StudioOrdersRoute,
  StudioPagesRoute: StudioPagesRoute,
  StudioProductsRoute: StudioProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
  ConferencesIndexRoute: ConferencesIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DocsAdminAwardsRoute: DocsAdminAwardsRoute,
  DocsAdminContentRoute: DocsAdminContentRoute,
  DocsAdminDashboardRoute: DocsAdminDashboardRoute,
  DocsAdminEventsRoute: DocsAdminEventsRoute,
  DocsAdminMembersRoute: DocsAdminMembersRoute,
  DocsAdminMembershipsRoute: DocsAdminMembershipsRoute,
  DocsAdminPaymentsRoute: DocsAdminPaymentsRoute,
  DocsAdminReportsRoute: DocsAdminReportsRoute,
  DocsAdminSettingsRoute: DocsAdminSettingsRoute,
  DocsAdminSubmissionsRoute: DocsAdminSubmissionsRoute,
  DocsAdminSupportRoute: DocsAdminSupportRoute,
  DocsAppendixWordpressRoute: DocsAppendixWordpressRoute,
  DocsArchitectureSitemapRoute: DocsArchitectureSitemapRoute,
  DocsGuidancePhasesRoute: DocsGuidancePhasesRoute,
  DocsGuidancePrioritiesRoute: DocsGuidancePrioritiesRoute,
  DocsOverviewReverseBriefRoute: DocsOverviewReverseBriefRoute,
  DocsStudioAwardsRoute: DocsStudioAwardsRoute,
  DocsStudioCollectionsRoute: DocsStudioCollectionsRoute,
  DocsStudioCustomersRoute: DocsStudioCustomersRoute,
  DocsStudioEventsRoute: DocsStudioEventsRoute,
  DocsStudioNewsRoute: DocsStudioNewsRoute,
  DocsStudioOrdersRoute: DocsStudioOrdersRoute,
  DocsStudioPagesRoute: DocsStudioPagesRoute,
  DocsStudioProductsRoute: DocsStudioProductsRoute,
  DocsVendorBriefRoute: DocsVendorBriefRoute,
  DocsAdminIndexRoute: DocsAdminIndexRoute,
  DocsAppendixIndexRoute: DocsAppendixIndexRoute,
  DocsArchitectureIndexRoute: DocsArchitectureIndexRoute,
  DocsGuidanceIndexRoute: DocsGuidanceIndexRoute,
  DocsStudioIndexRoute: DocsStudioIndexRoute,
  DocsVendorIndexRoute: DocsVendorIndexRoute,
  DocsArchitectureServicesAlgoliaRoute: DocsArchitectureServicesAlgoliaRoute,
  DocsArchitectureServicesAuth0Route: DocsArchitectureServicesAuth0Route,
  DocsArchitectureServicesKlaviyoRoute: DocsArchitectureServicesKlaviyoRoute,
  DocsArchitectureServicesSanityRoute: DocsArchitectureServicesSanityRoute,
  DocsArchitectureServicesShopifyRoute: DocsArchitectureServicesShopifyRoute,
  DocsArchitectureServicesIndexRoute: DocsArchitectureServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
