/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/conferences': typeof ConferencesRoute
  '/contacts': typeof ContactsRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store': typeof StoreRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/conferences': typeof ConferencesRoute
  '/contacts': typeof ContactsRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store': typeof StoreRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/conferences': typeof ConferencesRoute
  '/contacts': typeof ContactsRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store': typeof StoreRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/conferences'
    | '/contacts'
    | '/events'
    | '/news'
    | '/privacy-policy'
    | '/store'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/conferences'
    | '/contacts'
    | '/events'
    | '/news'
    | '/privacy-policy'
    | '/store'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/calendar'
    | '/cart'
    | '/conferences'
    | '/contacts'
    | '/events'
    | '/news'
    | '/privacy-policy'
    | '/store'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  CalendarRoute: typeof CalendarRoute
  CartRoute: typeof CartRoute
  ConferencesRoute: typeof ConferencesRoute
  ContactsRoute: typeof ContactsRoute
  EventsRoute: typeof EventsRoute
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  StoreRoute: typeof StoreRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  CalendarRoute: CalendarRoute,
  CartRoute: CartRoute,
  ConferencesRoute: ConferencesRoute,
  ContactsRoute: ContactsRoute,
  EventsRoute: EventsRoute,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  StoreRoute: StoreRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
